### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Kapral67** [pojntfx/xeus-cling-binaries#1]
Thanks for posting this. Makes it easier to run cpp notebooks on raspberry pi. Is it possible to use this technique to make binaries of this xeus kernel: https://github.com/jupyter-xeus/xeus-sql.git ?

**Comment by pojntfx** [comment]
Hi!

Glad to hear that it helps you. In theory, one could try and bundle xeus-sql as well; I've in fact tried to do so with xeus-sqlite, but failed (some weird segfaults ... there were no debug symbols so it was a bit hard to debug). I'll be sure to try it out with xeus-sql and post the results here ;)

**Comment by pojntfx** [comment]
@Kapral67 Alright, this seems doable: https://twitter.com/pojntfx/status/1367534220743225347

I'll be pushing changes to https://github.com/pojntfx/xeus-sql-binaries which will also provide the aarch64 binaries.

**Comment by pojntfx** [comment]
Closing as successfully implemented at https://github.com/pojntfx/xeus-sql-binaries, changes backported to this repository and downstream viability validated at https://github.com/pojntfx/pojde-ng/commit/34b38e66305db5203e2a6ade2380ea59fd0158e9. Thanks for your suggestion @Kapral67 :)
